### ISSUE TITLE
Cell Layout 이 깨집니다.

### ISSUE THREAD

**Issue by kimtaesu** [92pino/StoreCopy#1]
![image](https://user-images.githubusercontent.com/20927825/64472440-63700d00-d199-11e9-9410-97806bda889a.png)

**Comment by 92pino** [comment]
<img width="241" alt="스크린샷 2019-09-08 오전 3 18 15" src="https://user-images.githubusercontent.com/45158632/64478721-61cd3600-d1e7-11e9-9249-6fdcb406a2f4.png">

- resolved: #1
StoreCopy_tableView에서 해당 이슈사항 해결하였습니다.
